In [2]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5]

5

In [4]:
arr[5:8]

array([5, 6, 7])

In [6]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [7]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr2d[0][2]

3

In [9]:
arr2d[0,2]

3

In [10]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [14]:
a = np.arange(12)
print(a)
print(a.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [15]:
b = a.reshape((3,4))
print(b)
print(b.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [17]:
c = b.reshape((12,))
print(c)
print(c.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [19]:
x = np.arange(24).reshape((8,3))
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [23]:
x = np.linspace(1,10,6).reshape((3,2))
x

array([[ 1. ,  2.8],
       [ 4.6,  6.4],
       [ 8.2, 10. ]])

In [25]:
x = np.arange(24).reshape((8,3))
print(x)
x.T

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


array([[ 0,  3,  6,  9, 12, 15, 18, 21],
       [ 1,  4,  7, 10, 13, 16, 19, 22],
       [ 2,  5,  8, 11, 14, 17, 20, 23]])

In [27]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [29]:
data = np.random.randn(7,4)
data

array([[ 0.801087  , -0.10161775,  0.49144853,  1.52943518],
       [ 2.43392468, -0.0846231 , -0.45146157, -1.12536164],
       [-0.79964362,  1.19368811, -0.24480946, -0.50737916],
       [ 1.58709495,  0.01645074, -0.62292845, -1.66035277],
       [-1.11336355,  0.9553983 ,  0.54353781, -0.10886824],
       [-0.74697139, -1.08763764, -1.5340989 , -1.62146476],
       [ 0.1326989 ,  0.87447927,  0.77003659,  0.56967585]])

In [31]:
data[[True,False,True,False,False,True,False]]

array([[ 0.801087  , -0.10161775,  0.49144853,  1.52943518],
       [-0.79964362,  1.19368811, -0.24480946, -0.50737916],
       [-0.74697139, -1.08763764, -1.5340989 , -1.62146476]])

In [32]:
data < 0

array([[False,  True, False, False],
       [False,  True,  True,  True],
       [ True, False,  True,  True],
       [False, False,  True,  True],
       [ True, False, False,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [36]:
data[data<0] = 0
data

array([[0.801087  , 0.        , 0.49144853, 1.52943518],
       [2.43392468, 0.        , 0.        , 0.        ],
       [0.        , 1.19368811, 0.        , 0.        ],
       [1.58709495, 0.01645074, 0.        , 0.        ],
       [0.        , 0.9553983 , 0.54353781, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.1326989 , 0.87447927, 0.77003659, 0.56967585]])