In [2]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5]

5

In [4]:
arr[5:8]

array([5, 6, 7])

In [6]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [7]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr2d[0][2]

3

In [9]:
arr2d[0,2]

3

In [10]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [14]:
a = np.arange(12)
print(a)
print(a.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [15]:
b = a.reshape((3,4))
print(b)
print(b.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [17]:
c = b.reshape((12,))
print(c)
print(c.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
