In [3]:
import numpy as np
#陣列運算
oneArray = np.array([1,2,3,4,5])
oneArray * 10 / 5

array([ 2.,  4.,  6.,  8., 10.])

In [4]:
#陣列運算
twoArray = np.array([9, 8, 7, 6, 5])
oneArray + twoArray

array([10, 10, 10, 10, 10])

In [7]:
#統計
np.sum(oneArray),np.sum(twoArray)


(15, 35)

In [9]:
#科學運算
np.log10(oneArray), np.log10(twoArray)

(array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ]),
 array([0.95424251, 0.90308999, 0.84509804, 0.77815125, 0.69897   ]))