In [4]:
#list的運算,需要利用迴圈
import random
chinese = [random.randint(60, 100) for _ in range(50)]
english = [random.randint(60, 100) for _ in range(50)]

result = []
for i in range(50):
    total = chinese[i] + english[i]
    result.append(total)

result

[177,
 144,
 154,
 164,
 128,
 142,
 152,
 163,
 191,
 175,
 146,
 154,
 158,
 166,
 158,
 187,
 185,
 149,
 153,
 162,
 163,
 174,
 174,
 173,
 142,
 163,
 180,
 143,
 165,
 162,
 145,
 134,
 174,
 150,
 161,
 141,
 160,
 155,
 138,
 150,
 179,
 144,
 138,
 161,
 166,
 173,
 160,
 138,
 145,
 159]

In [10]:
#使用numpy,陣列運算

import numpy as np
chinese = np.random.randint(60, high=100, size=50)
english = np.random.randint(60, high=100, size=50)
result = chinese + english
result


array([151, 145, 130, 142, 158, 155, 129, 150, 162, 140, 179, 160, 140,
       141, 137, 149, 152, 155, 161, 155, 159, 131, 170, 121, 126, 170,
       161, 158, 178, 171, 170, 163, 138, 155, 140, 137, 133, 170, 129,
       136, 159, 130, 156, 183, 145, 164, 188, 180, 188, 157])

In [20]:
#50個學生,5個分數
import numpy as np

students = np.random.randint(60,high=100,size=(50, 5)) #2維
print(students)
sum = np.sum(students,axis=1)
average = np.average(students,axis=1)
print(sum)
print("============")
print(average)

[[96 62 62 75 75]
 [89 68 71 81 81]
 [95 74 76 64 92]
 [97 69 64 98 82]
 [76 90 99 97 98]
 [66 97 72 97 60]
 [71 72 64 87 93]
 [83 93 84 62 77]
 [84 80 99 64 88]
 [97 86 70 70 66]
 [82 82 67 78 86]
 [60 64 84 79 93]
 [74 81 61 94 79]
 [97 80 89 98 78]
 [86 92 81 80 95]
 [95 81 66 61 74]
 [77 83 97 62 74]
 [65 80 82 60 81]
 [99 79 63 74 89]
 [69 89 90 82 95]
 [66 68 66 90 97]
 [90 87 83 97 71]
 [99 69 73 97 84]
 [90 64 60 60 89]
 [78 81 98 86 64]
 [83 80 92 78 82]
 [62 86 70 62 75]
 [80 96 89 96 75]
 [67 64 82 76 94]
 [60 91 95 70 77]
 [65 66 87 62 93]
 [99 69 81 91 76]
 [88 81 99 92 74]
 [69 87 84 92 79]
 [95 86 83 95 98]
 [97 78 91 75 77]
 [60 65 91 98 84]
 [84 71 75 80 80]
 [97 72 80 75 82]
 [60 60 86 97 74]
 [63 99 81 65 84]
 [74 70 60 96 60]
 [71 94 81 80 97]
 [82 87 85 93 90]
 [98 61 92 88 77]
 [85 78 87 72 71]
 [92 62 61 76 66]
 [92 92 90 99 78]
 [68 63 89 65 93]
 [63 79 88 77 87]]
[370 390 401 410 460 392 387 399 415 389 395 380 389 442 434 377 393 368
 404 425 387 428 422 363 4

In [26]:
for i in range(50):
    print(students[i])

[96 62 62 75 75]
[89 68 71 81 81]
[95 74 76 64 92]
[97 69 64 98 82]
[76 90 99 97 98]
[66 97 72 97 60]
[71 72 64 87 93]
[83 93 84 62 77]
[84 80 99 64 88]
[97 86 70 70 66]
[82 82 67 78 86]
[60 64 84 79 93]
[74 81 61 94 79]
[97 80 89 98 78]
[86 92 81 80 95]
[95 81 66 61 74]
[77 83 97 62 74]
[65 80 82 60 81]
[99 79 63 74 89]
[69 89 90 82 95]
[66 68 66 90 97]
[90 87 83 97 71]
[99 69 73 97 84]
[90 64 60 60 89]
[78 81 98 86 64]
[83 80 92 78 82]
[62 86 70 62 75]
[80 96 89 96 75]
[67 64 82 76 94]
[60 91 95 70 77]
[65 66 87 62 93]
[99 69 81 91 76]
[88 81 99 92 74]
[69 87 84 92 79]
[95 86 83 95 98]
[97 78 91 75 77]
[60 65 91 98 84]
[84 71 75 80 80]
[97 72 80 75 82]
[60 60 86 97 74]
[63 99 81 65 84]
[74 70 60 96 60]
[71 94 81 80 97]
[82 87 85 93 90]
[98 61 92 88 77]
[85 78 87 72 71]
[92 62 61 76 66]
[92 92 90 99 78]
[68 63 89 65 93]
[63 79 88 77 87]
