In [3]:
#建立ndArray
import numpy
arr1 = numpy.array([1,2,3,4,5])
type(arr1)

numpy.ndarray

In [5]:
#list和ndArray的差別
#資料集內容要*2
#list必需使用for...in存取元素
#ndArray使用陣列運算

list1 = [4,5,6,7,8]
result = []
for value in list1:
    result.append(value * 2)
result


[8, 10, 12, 14, 16]

In [6]:
#comprehension

list1 = [4,5,6,7,8]

result = [value*2 for value in list1]
result

[8, 10, 12, 14, 16]

In [9]:
#numpy整體的陣列運算

import numpy as np
array = np.array([4, 5, 6, 7, 8])
array * 2

array([ 8, 10, 12, 14, 16])

In [11]:
import numpy as np
scores_arr = np.random.randint(60,101,size=(50,5))
scores_arr

array([[ 71,  64,  69, 102, 102],
       [ 81,  65,  93,  74,  62],
       [ 98, 100,  66, 101,  97],
       [ 65,  89,  87,  90,  90],
       [ 71,  89,  99,  77,  87],
       [ 97,  82,  66,  78,  98],
       [101,  71,  72,  64,  62],
       [ 66,  83,  70,  74,  78],
       [ 77,  88,  86,  99,  65],
       [ 70,  91,  86,  99,  95],
       [ 77,  65,  77,  97,  96],
       [ 62,  72,  76,  90,  72],
       [ 97,  98,  95,  72,  69],
       [ 91,  70,  94,  80,  91],
       [ 97, 101,  67,  76,  70],
       [ 80,  89,  73,  67,  67],
       [ 74,  85,  78,  81,  79],
       [ 63,  95,  75,  75,  83],
       [ 91,  86,  86,  79,  70],
       [ 86,  93,  93,  83,  88],
       [ 70,  96,  72,  63,  66],
       [100,  77,  96,  81,  67],
       [ 84,  74,  93,  64, 101],
       [ 80,  75,  63,  62,  74],
       [ 80,  78, 102,  90,  99],
       [102,  90,  93,  68,  70],
       [ 70,  68,  90,  75,  66],
       [ 86,  73,  92,  75,  84],
       [ 62,  94,  93,  88,  81],
       [ 67,  

In [12]:
#for in ndarray

for item in scores_arr:
    print(item)

[ 69  62  67 100 100]
[79 63 91 72 60]
[96 98 64 99 95]
[63 87 85 88 88]
[69 87 97 75 85]
[95 80 64 76 96]
[99 69 70 62 60]
[64 81 68 72 76]
[75 86 84 97 63]
[68 89 84 97 93]
[75 63 75 95 94]
[60 70 74 88 70]
[95 96 93 70 67]
[89 68 92 78 89]
[95 99 65 74 68]
[78 87 71 65 65]
[72 83 76 79 77]
[61 93 73 73 81]
[89 84 84 77 68]
[84 91 91 81 86]
[68 94 70 61 64]
[98 75 94 79 65]
[82 72 91 62 99]
[78 73 61 60 72]
[ 78  76 100  88  97]
[100  88  91  66  68]
[68 66 88 73 64]
[84 71 90 73 82]
[60 92 91 86 79]
[65 90 77 71 78]
[74 68 97 80 79]
[91 69 97 78 82]
[70 78 73 85 68]
[99 89 81 65 91]
[88 86 85 75 84]
[95 75 76 75 70]
[83 66 75 77 81]
[67 74 78 86 92]
[72 86 94 85 99]
[73 79 86 73 64]
[82 84 75 95 83]
[73 73 90 68 93]
[ 74  97  79 100  95]
[68 79 77 65 89]
[67 85 64 91 91]
[75 95 80 84 77]
[67 60 96 61 68]
[81 94 88 65 60]
[ 75 100  98  90  99]
[70 67 72 95 89]


In [14]:
np.arange(0,1000,0.5)

array([0.000e+00, 5.000e-01, 1.000e+00, ..., 9.985e+02, 9.990e+02,
       9.995e+02])

In [16]:
x=np.linspace(-3,3,50)
len(x)

50

In [17]:
#檢查形狀
x.shape

(50,)

In [18]:
#檢查維度
x.ndim

1

In [19]:
#檢查元素數量
x.size

50

In [20]:
#檢查資料類形
x.dtype

dtype('float64')